In [9]:
import numpy as np
from turing_21_matrix_operations.main import convolution2d, window1d, transpose2d, create_random_matrix

In [12]:
# Transposition
random_matrix = create_random_matrix(3, 3)

print(random_matrix)

input_matrix = [
    [1, 2],
    [4, 5],
    [2, 15]
  ]

print(transpose2d(input_matrix=random_matrix))
print(transpose2d(input_matrix=input_matrix))

[[8, 5, 8], [8, 2, 9], [5, 0, 6]]
[[8, 8, 5], [5, 2, 0], [8, 9, 6]]
[[1, 4, 2], [2, 5, 15]]


In [13]:
# Windowing
windowed = window1d(list(range(10)), size=2, shift=2, stride=2)
windowed

[[0, 2], [2, 4], [4, 6], [6, 8]]

In [16]:
# input_array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
input_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

windowed = window1d(input_array=input_array, size=2, shift=3, stride=2)
windowed

[array([1, 3]), array([4, 6]), array([7, 9])]

In [6]:
# new_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# new_array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
new_array = np.random.randint(0, 20, 20)

windowed = window1d(new_array, size=2, shift=2, stride=2)
windowed

[array([ 8, 10]),
 array([10, 13]),
 array([13,  2]),
 array([2, 4]),
 array([ 4, 15]),
 array([15,  6]),
 array([6, 8]),
 array([8, 3]),
 array([3, 9])]

In [19]:
# Convolution
input_matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
kernel = np.array([
    [1, 1.2],
    [0, 1]
])
convolved = convolution2d(input_matrix=input_matrix, kernel=kernel, stride=2)
convolved

array([[ 9.4, 15.8],
       [35. , 41.4]])

Given an array "nums" containing "n" distinct numbers in the range [0, n], return the only number in the range that is missing from the array.

nums = [3,0,1] output = 2

nums = [9,6,4,2,3,5,7,0,1] output = 8

nums = [0,1] Output = 2

In [21]:
nums = [3, 0, 1]
list_new = [num for num in range(len(nums)+1) if num not in set(nums)]
list_new

[2]

In [34]:
from collections import Counter

nums = [3, 0, 1]
# output = 2
# nums_sorted = nums.sort()
nums_sorted = sorted(nums)
listed = list(range(len(nums)+1))
print(listed)
print(nums_sorted)
output = nums_sorted not in listed
print(output)

a = Counter(listed)
b = Counter(nums_sorted)
c = a-b
print(c)
# print(c.keys())
output = list(c.keys())[0]
output

[0, 1, 2, 3]
[0, 1, 3]
True
Counter({2: 1})


2

In [ ]:
nums = [9,6,4,2,3,5,7,0,1] 

nums_sorted = sorted(nums)
listed = list(range(len(nums)+1))


a = Counter(listed)
b = Counter(nums_sorted)
c = a-b
print(c)
output = list(c.keys())[0]
output

solutions:
  * Math to sum input array and compare to sum or full list new_array
  * Coutner both lists and find frequency of 1
  * for loop looping through lists and finding mismatches between lists

calculate average on list of numbers
use function
use class

In [25]:
# Using Counter: Counter class from the collections module to count the occurrences of each number in both the nums array and the full array of numbers from 0 to n. 
# The missing number will have a frequency difference of 1.
from collections import Counter

def find_missing_number_counter(nums):
    n = len(nums)
    full_nums = list(range(n+1))
    count_nums = Counter(nums)
    count_full = Counter(full_nums)
    
    for number in count_full:
        if count_full[number] - count_nums[number] == 1:
            return number

nums = [9,6,4,2,3,5,7,0,1]
print(find_missing_number_counter(nums))  # 8


8


In [35]:
# Using a For Loop: In this approach, we loop through the list of numbers from 0 to n and the nums array to find mismatches.
def find_missing_number_loop(nums):
    n = len(nums)
    full_nums = list(range(n+1))
    
    for i in full_nums:
        if i not in nums:
            return i

print(find_missing_number_loop(nums))  # 2


2


In [27]:
# Using math: Missing number=Expected sum−Actual sum
# Expected sum is derived from the sum of the first n natural numbers.
def find_missing_number(nums):
    n = len(nums)
    expected_sum = n * (n + 1) // 2
    actual_sum = sum(nums)
    return expected_sum - actual_sum

# nums = [3, 0, 1]
nums = [9,6,4,2,3,5,7,0,1]
print(find_missing_number(nums))  # 2

8


In [24]:
# Math Approach using Sum:
def find_missing_number_sum(nums):
    n = len(nums)
    full_sum = sum(range(n+1))
    return full_sum - sum(nums)

# nums = [3, 0, 1]
nums = [9,6,4,2,3,5,7,0,1]
print(find_missing_number_sum(nums))  # 2

8


In [18]:
# XOR Approach: Utilize the property that x XOR x = 0. XOR all the numbers in the array and all numbers from 0 to n. The result will be the missing number.
def find_missing_number_xor(nums):
    xor_total = 0
    for i in range(len(nums) + 1):
        xor_total ^= i

    # A⊕A=0 (Any number XOR'd with itself will result in 0.)
    for num in nums:
        xor_total ^= num

    return xor_total

# nums = [3, 0, 1]
nums = [9,6,4,2,3,5,7,0,1]
print(find_missing_number_xor(nums))  # 2



8


In [19]:
# Set Approach: Convert the list to a set and then check for the first missing integer from the set.
def find_missing_number_set(nums):
    num_set = set(nums)
    n = len(nums) + 1
    for number in range(n):
        if number not in num_set:
            return number

# nums = [3, 0, 1]
nums = [9,6,4,2,3,5,7,0,1]
print(find_missing_number_set(nums))  # 2



8


In [22]:
nums = [9,6,4,2,3,5,7,0,1]

for number in range(len(nums)+1):
        if number not in set(nums):
            print(number)
            
output = [number for number in range(len(nums)+1) if number not in set(nums)]
output

8


[8]

In [30]:
# Create a matrix from list:
  
listings = [1, 2, 3, 4, 5, 6, 7, 8, 9]
matrix_size = 3  # Define the size of the matrix (3x3)

matrix = [listings[i:i + matrix_size] for i in range(0, len(listings), matrix_size)]
matrix
  

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
# Class exercise
Create a class of books and a class of library catalog.
Be able to add a Book to Library.
And add an option/function to find a book in a library by author.


In [36]:
class Book():
  def __init__(self, title, author):
    self.title = title
    self.author = author
  
  # calls Print output
  def __str__(self):
    return f"'{self.title}' by {self.author}"

    
class Library:
    def __init__(self):
        self.books = []

    def add_book(self, book):
        if isinstance(book, Book):
            self.books.append(book)
        else:
            print("Only a Book instance can be added to the library.")

    def find_books_by_author(self, author_name):
        books_by_author = [book for book in self.books if book.author == author_name]
        return books_by_author
    
    def __str__(self):
        # Join the string representation of each book in the library
        return "\n".join(str(book) for book in self.books)


book1 = Book("The Great Gatsby", "F. Scott Fitzgerald")
book2 = Book("1984", "George Orwell")
book3 = Book("Brave New World", "Aldous Huxley")
book4 = Book("Homage to Catalonia", "George Orwell")

library = Library()
library.add_book(book1)
library.add_book(book2)
library.add_book(book3)
library.add_book(book4)

# library.books
# print(library.books)
print(library)
print(book1, "\n")

# Find books by George Orwell
orwell_books = library.find_books_by_author("George Orwell")
for book in orwell_books:
    print(book)
    # print(book.title)

'The Great Gatsby' by F. Scott Fitzgerald
'1984' by George Orwell
'Brave New World' by Aldous Huxley
'Homage to Catalonia' by George Orwell
'The Great Gatsby' by F. Scott Fitzgerald 

'1984' by George Orwell
'Homage to Catalonia' by George Orwell


In [64]:
# calculate average on list of numbers
numbers = [10, 20, 30, 40, 50]

# Without using a function:
average = sum(numbers) / len(numbers)
print(average)  # Output: 30.0

30.0


In [65]:
# Using a function:
def calculate_average(nums):
    return sum(nums) / len(nums)

print(calculate_average(numbers))  # Output: 30.0

30.0


In [66]:
# Using a class:
class NumberList:
    def __init__(self, numbers):
        self.numbers = numbers
    
    def average(self):
        return sum(self.numbers) / len(self.numbers)

number_list = NumberList(numbers)
print(number_list.average())  # Output: 30.0


30.0


In [67]:
class RunningAverage:
    def __init__(self):
        self.total = 0
        self.count = 0

    def add_number(self, num):
        self.total += num
        self.count += 1
        return self.total / self.count

    def get_average(self):
        if self.count == 0:
            return 0
        return self.total / self.count

# Usage
avg_calculator = RunningAverage()
print(avg_calculator.add_number(10))  # 10.0
print(avg_calculator.add_number(20))  # 15.0
print(avg_calculator.add_number(30))  # 20.0
print(avg_calculator.get_average())   # 20.0
print(avg_calculator.add_number(40))  # 25.0


10.0
15.0
20.0
20.0
25.0


In [68]:
def calculate_average(nums):
    total = 0
    count = 0
    for num in nums:
        total += num
        count += 1
    return total / count if count != 0 else 0  # Added a check to avoid division by zero

numbers = [10, 20, 30, 40, 50]
print(calculate_average(numbers))  # Output: 30.0


30.0


In [ ]:
You are to implement a function normalize_matrix in Python, using standart library, that takes a 2D list of real numbers (matrix) and normalizes the values in the matrix to the range [0, 1].
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
For normalization use:
normalized_value = (value - min_value) / (max_value - min_value)



In [45]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]

flat_matrix = [value for row in matrix for value in row]
print(flat_matrix)


flat_matrix2 = list()
for i in matrix:
  flat_matrix2.extend(i)
print(flat_matrix2)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [51]:
flat_matrix = []
for row in matrix:
    for item in row:
        flat_matrix.append(item)
        
flat_matrix

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [53]:
flat_matrix = np.array(matrix).flatten()
flat_matrix

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
def normalize_matrix(matrix):
    # Flatten the matrix to find the global min and max
    flat_matrix = [value for row in matrix for value in row]
    min_value = min(flat_matrix)
    max_value = max(flat_matrix)

    # Normalize each element in the matrix
    normalized_matrix = [[(value - min_value) / (max_value - min_value) for value in row] for row in matrix]
    return normalized_matrix

# Example matrix
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# Normalize the matrix
normalized_matrix = normalize_matrix(matrix)
print(normalized_matrix)


[[0.0, 0.125, 0.25], [0.375, 0.5, 0.625], [0.75, 0.875, 1.0]]


In [47]:
def normalize_matrix_beginner(matrix):
    flat_matrix = []
    for row in matrix:
        for item in row:
            flat_matrix.append(item)
    min_value = min(flat_matrix)
    max_value = max(flat_matrix)

    normalized_matrix = []
    for row in matrix:
        normalized_row = []
        for item in row:
            normalized_item = (item - min_value) / (max_value - min_value)
            normalized_row.append(normalized_item)
        normalized_matrix.append(normalized_row)
    return normalized_matrix

normalized_matrix = normalize_matrix_beginner(matrix)
normalized_matrix

[[0.0, 0.125, 0.25], [0.375, 0.5, 0.625], [0.75, 0.875, 1.0]]

In [49]:
def normalize_matrix_intermediate(matrix):
    min_value = min(min(row) for row in matrix)
    max_value = max(max(row) for row in matrix)

    normalized_matrix = [[(item - min_value) / (max_value - min_value) for item in row] for row in matrix]
    return normalized_matrix


normalized_matrix = normalize_matrix_intermediate(matrix)
normalized_matrix

[[0.0, 0.125, 0.25], [0.375, 0.5, 0.625], [0.75, 0.875, 1.0]]

In [50]:
import numpy as np

def normalize_matrix_advanced(matrix):
    flat_matrix = np.array(matrix).flatten()
    min_value, max_value = np.min(flat_matrix), np.max(flat_matrix)
    
    normalize = lambda item: (item - min_value) / (max_value - min_value)
    return np.vectorize(normalize)(matrix).tolist()

normalized_matrix = normalize_matrix_intermediate(matrix)
normalized_matrix

[[0.0, 0.125, 0.25], [0.375, 0.5, 0.625], [0.75, 0.875, 1.0]]

# Matrix Transpose

In [ ]:
input_matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

for row in input_matrix:
  print(row)

In [ ]:
for i in range(len(input_matrix[0])):
  print([row[i] for row in input_matrix])

In [ ]:
transposed = [[row[i] for row in input_matrix] for i in range(len(input_matrix[0]))]
transposed

In [ ]:
input_matrix = [
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0]
]

# ZIP creates tuples
# transposed_matrix = list(zip(*input_matrix))
transposed_matrix = [list(row) for row in zip(*input_matrix)]

transposed_matrix


# Windowing

In [ ]:
# Trial
def window1d(*, input_array: Union[List[float], np.ndarray], size: int, shift: int = 1, stride: int = 1) -> Union[List[List[float]], List[np.ndarray]]:
    windows = []
    i = 0
    
    # Continue until the end of the array is reached
    while i + size * stride <= len(input_array):
        window = []
        j = 0
        
        while len(window) < size and (i + j) < len(input_array):
            window.append(input_array[i + j])
            j += stride
        
        # If the window size is as expected, append it to the windows list
        if len(window) == size:
            if isinstance(input_array, np.ndarray):
                windows.append(np.array(window))
            else:
                windows.append(window)
        
        # Shift to the next window using the shift provided
        i += shift
        
    return windows

new_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
type(new_array)

windowed_data = window1d(input_array=new_array, size=3, shift=2, stride=2)
windowed_data


In [ ]:
input_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
size = 3
stride = 2
shift = 2

num_windows = (len(input_array) - size * stride) // shift + 1
#                           10 - 3 * 2 // 2 + 1
print(len(input_array))
print(num_windows)

print(input_array[0:10:2])

# Convolution and Cross correlation

In [ ]:
import numpy as np

def convolution2d(input_matrix: np.ndarray, kernel: np.ndarray, stride: int = 1) -> np.ndarray:
    
    # Ensure inputs size, shift, and stride are positive
    if stride <= 0 or not isinstance(stride, int):
        raise ValueError("Stride must be a positive integer.")
    
    # Ensure inputs are 2D arrays
    if not isinstance(input_matrix, np.ndarray) or input_matrix.ndim != 2 or not isinstance(kernel, np.ndarray) or kernel.ndim != 2:
        raise TypeError("input_matrix and kernel must 2D np.ndarray.")
    
    input_rows, input_cols = input_matrix.shape
    kernel_rows, kernel_cols = kernel.shape

    # Ensure matrix and kernel shapes are compatible
    if input_rows <= kernel_rows or input_cols <= kernel_cols:
        raise ValueError("Input matrix dimensions must be greater or equal to kernel dimensions.")
    
    output_rows = (input_rows - kernel_rows) // stride + 1
    output_cols = (input_cols - kernel_cols) // stride + 1
    
    # Create an empty output matrix with zeros
    output = np.zeros((output_rows, output_cols))
    
    # Slide the kernel over the input matrix and compute the cross-correlation
    for i in range(output_rows):
        for j in range(output_cols):
            sum_val = 0
            for x in range(kernel_rows):
                for y in range(kernel_cols):
                    # sum_val += input_matrix[i*stride + x][j*stride + y] * kernel[x][y]
                    matrix = input_matrix[i*stride + x][j*stride + y]
                    sum_val += matrix * kernel[x][y]
            output[i][j] = sum_val
            
            
    # for i in range(0, output_rows):
    #     for j in range(0, output_cols):
    #         output_matrix[i, j] = np.sum(input_matrix[i*stride:i*stride+kernel_rows, j*stride:j*stride+kernel_cols] * kernel)
            
    
    # return np.array(output)
    return output

# Test the function
input_mat = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
    # [17, 18, 19, 20]
])
kern = np.array([
    [1, 0],
    [0, -1]
    # [1, 1]
])
result = convolution2d(input_mat, kern, stride=1)
result

# Test the function
# result_simple = convolution2d(input_mat, kern, stride=2)
# result_simple


In [ ]:
Let's break down how the convolution2d function works:

We start by determining the dimensions of both the input matrix and the kernel.
The dimensions of the output matrix are computed based on the size of the input matrix, the size of the kernel, and the stride.
We initialize an output matrix filled with zeros of the computed dimensions.
We slide the kernel over the input matrix, using the specified stride. For each position of the kernel, we calculate the element-wise product between the sub-matrix of the input (covered by the kernel) and the kernel itself. The sum of these products gives the value at the corresponding position in the output matrix.
Once we've iterated over the entire input matrix, we return the populated output matrix.

In [8]:
import numpy as np

def convolution2d(input_matrix: np.ndarray, kernel: np.ndarray, stride: int = 1) -> np.ndarray:
    if stride <= 0 or not isinstance(stride, int):
        raise ValueError("Stride must be a positive integer.")

    if not isinstance(input_matrix, np.ndarray) or input_matrix.ndim != 2 or not isinstance(kernel, np.ndarray) or kernel.ndim != 2:
        raise TypeError("input_matrix and kernel must 2D np.ndarray.")
    
    # Get the dimensions of the input matrix and kernel
    input_rows = len(input_matrix)
    input_cols = len(input_matrix[0])
    kernel_rows = len(kernel)
    kernel_cols = len(kernel[0])
    
    # input_rows, input_cols = input_matrix.shape
    # kernel_rows, kernel_cols = kernel.shape
    
    # Compute the dimensions of the output matrix
    output_rows = (input_rows - kernel_rows) // stride + 1
    output_cols = (input_cols - kernel_cols) // stride + 1
    
    # Create an empty output matrix with zeros
    output_matrix = np.zeros((output_rows, output_cols))
        
    # Slide the kernel over the input matrix and compute the cross-correlation
    for i in range(output_rows):
        for j in range(output_cols):
            sum_val = 0
            for x in range(kernel_rows):
                for y in range(kernel_cols):
                    # Print the current element of input_matrix and kernel being multiplied
                    print(f"input_matrix[{i*stride + x}][{j*stride + y}] ({input_matrix[i*stride + x][j*stride + y]}) * kernel[{x}][{y}] ({kernel[x][y]})")
                    
                    sum_val += input_matrix[i*stride + x][j*stride + y] * kernel[x][y]
            
            # Print the calculated sum for the current position in the output matrix
            print(f"\nSum for output_matrix[{i}][{j}] = {sum_val}\n{'='*30}\n")
            output_matrix[i][j] = sum_val
    
    return np.array(output_matrix)

# Test the function
input_mat = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
kern = np.array([
    [1, 0],
    [0, -1]
])
result = convolution2d(input_mat, kern, stride=2)
print(result)


input_matrix[0][0] (1) * kernel[0][0] (1)
input_matrix[0][1] (2) * kernel[0][1] (0)
input_matrix[1][0] (5) * kernel[1][0] (0)
input_matrix[1][1] (6) * kernel[1][1] (-1)

Sum for output_matrix[0][0] = -5

input_matrix[0][2] (3) * kernel[0][0] (1)
input_matrix[0][3] (4) * kernel[0][1] (0)
input_matrix[1][2] (7) * kernel[1][0] (0)
input_matrix[1][3] (8) * kernel[1][1] (-1)

Sum for output_matrix[0][1] = -5

input_matrix[2][0] (9) * kernel[0][0] (1)
input_matrix[2][1] (10) * kernel[0][1] (0)
input_matrix[3][0] (13) * kernel[1][0] (0)
input_matrix[3][1] (14) * kernel[1][1] (-1)

Sum for output_matrix[1][0] = -5

input_matrix[2][2] (11) * kernel[0][0] (1)
input_matrix[2][3] (12) * kernel[0][1] (0)
input_matrix[3][2] (15) * kernel[1][0] (0)
input_matrix[3][3] (16) * kernel[1][1] (-1)

Sum for output_matrix[1][1] = -5

[[-5. -5.]
 [-5. -5.]]
