In [1]:
import numpy as np
from src.main import convolution2d, window1d, transpose2d, create_random_matrix

In [2]:
# Transposition
random_matrix = create_random_matrix(3, 4)

print(random_matrix)

input_matrix = [
    [1, 2],
    [4, 5],
    [2, 15]
  ]

print(transpose2d(input_matrix=random_matrix))
print(transpose2d(input_matrix=input_matrix))

[[7, 1, 8, 8], [4, 1, 7, 8], [7, 1, 7, 0]]
[[7, 4, 7], [1, 1, 1], [8, 7, 7], [8, 8, 0]]
[[1, 4, 2], [2, 5, 15]]


In [3]:
# Windowing
windowed = window1d(list(range(10)), size=2, shift=2, stride=2)
windowed

[[0, 2], [2, 4], [4, 6], [6, 8]]

In [4]:
# input_array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
input_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

windowed = window1d(input_array=input_array, size=2, shift=2, stride=2)
windowed

[array([1, 3]), array([3, 5]), array([5, 7]), array([7, 9])]

In [5]:
# new_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# new_array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
new_array = np.random.randint(0, 20, 20)

windowed = window1d(new_array, size=2, shift=2, stride=2)
windowed

[array([3, 1]),
 array([1, 0]),
 array([ 0, 18]),
 array([18,  4]),
 array([4, 9]),
 array([ 9, 18]),
 array([18, 10]),
 array([10,  4]),
 array([ 4, 13])]

In [6]:
# Convolution
input_matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
kernel = np.array([
    [1, 1.2],
    [0, 1]
])
convolved = convolution2d(input_matrix=input_matrix, kernel=kernel, stride=2)
convolved

array([[ 9.4, 15.8],
       [35. , 41.4]])

Given an array "nums" containing "n" distinct numbers in the range [0, n], return the only number in the range that is missing from the array.

In [ ]:
from collections import Counter

nums = [3, 0, 1]
# output = 2
# nums_sorted = nums.sort()
nums_sorted = sorted(nums)
listed = list(range(len(nums)+1))
print(listed)
print(nums_sorted)
output = nums_sorted not in listed
print(output)

a = Counter(listed)
b = Counter(nums_sorted)
c = a-b
print(c)
# print(c.keys())
output = list(c.keys())[0]
output

In [ ]:
nums = [9,6,4,2,3,5,7,0,1] 

nums_sorted = sorted(nums)
listed = list(range(len(nums)+1))


a = Counter(listed)
b = Counter(nums_sorted)
c = a-b
print(c)
output = list(c.keys())[0]
output

solutions:
  * Math to sum input array and compare to sum or full list new_array
  * Coutner both lists and find frequency of 1
  * for loop looping through lists and finding mismatches between lists

calculate average on list of numbers
use function
use class

create a class of books
a class of library catalog
and be able to add a book to library
and add an ability to find a book in a library by author


In [ ]:
Given an array "nums" containing "n" distinct numbers in the range [0, n], return the only number in the range that is missing from the array.

nums = [3,0,1] output = 2

nums = [9,6,4,2,3,5,7,0,1] output = 8

nums = [0,1] Output = 2







In [8]:
# Test the function with the provided example
test_input_matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
test_kernel = np.array([[1, 0], [1, 0]])

# test_kernel= np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
# test_input_matrix = np.array([[1, 0], [1, 0]])

test_stride = 2
convolved_output = convolution2d(test_input_matrix, test_kernel, test_stride)
convolved_output


array([[ 6., 10.],
       [22., 26.]])

# Matrix Transpose

In [ ]:
input_matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

for row in input_matrix:
  print(row)

In [ ]:
for i in range(len(input_matrix[0])):
  print([row[i] for row in input_matrix])

In [ ]:
transposed = [[row[i] for row in input_matrix] for i in range(len(input_matrix[0]))]
transposed

In [ ]:
input_matrix = [
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0]
]

# ZIP creates tuples
# transposed_matrix = list(zip(*input_matrix))
transposed_matrix = [list(row) for row in zip(*input_matrix)]

transposed_matrix


# Windowing

In [ ]:
# Trial
def window1d(*, input_array: Union[List[float], np.ndarray], size: int, shift: int = 1, stride: int = 1) -> Union[List[List[float]], List[np.ndarray]]:
    windows = []
    i = 0
    
    # Continue until the end of the array is reached
    while i + size * stride <= len(input_array):
        window = []
        j = 0
        
        while len(window) < size and (i + j) < len(input_array):
            window.append(input_array[i + j])
            j += stride
        
        # If the window size is as expected, append it to the windows list
        if len(window) == size:
            if isinstance(input_array, np.ndarray):
                windows.append(np.array(window))
            else:
                windows.append(window)
        
        # Shift to the next window using the shift provided
        i += shift
        
    return windows

new_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
type(new_array)

windowed_data = window1d(input_array=new_array, size=3, shift=2, stride=2)
windowed_data


In [ ]:
input_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
size = 3
stride = 2
shift = 2

num_windows = (len(input_array) - size * stride) // shift + 1
#                           10 - 3 * 2 // 2 + 1
print(len(input_array))
print(num_windows)

print(input_array[0:10:2])

# Convolution and Cross correlation

In [ ]:
import numpy as np

def convolution2d(input_matrix: np.ndarray, kernel: np.ndarray, stride: int = 1) -> np.ndarray:
    
    # Ensure inputs size, shift, and stride are positive
    if stride <= 0 or not isinstance(stride, int):
        raise ValueError("Stride must be a positive integer.")
    
    # Ensure inputs are 2D arrays
    if not isinstance(input_matrix, np.ndarray) or input_matrix.ndim != 2 or not isinstance(kernel, np.ndarray) or kernel.ndim != 2:
        raise TypeError("input_matrix and kernel must 2D np.ndarray.")
    
    input_rows, input_cols = input_matrix.shape
    kernel_rows, kernel_cols = kernel.shape

    # Ensure matrix and kernel shapes are compatible
    if input_rows <= kernel_rows or input_cols <= kernel_cols:
        raise ValueError("Input matrix dimensions must be greater or equal to kernel dimensions.")
    
    output_rows = (input_rows - kernel_rows) // stride + 1
    output_cols = (input_cols - kernel_cols) // stride + 1
    
    # Create an empty output matrix with zeros
    output = np.zeros((output_rows, output_cols))
    
    # Slide the kernel over the input matrix and compute the cross-correlation
    for i in range(output_rows):
        for j in range(output_cols):
            sum_val = 0
            for x in range(kernel_rows):
                for y in range(kernel_cols):
                    # sum_val += input_matrix[i*stride + x][j*stride + y] * kernel[x][y]
                    matrix = input_matrix[i*stride + x][j*stride + y]
                    sum_val += matrix * kernel[x][y]
            output[i][j] = sum_val
            
            
    # for i in range(0, output_rows):
    #     for j in range(0, output_cols):
    #         output_matrix[i, j] = np.sum(input_matrix[i*stride:i*stride+kernel_rows, j*stride:j*stride+kernel_cols] * kernel)
            
    
    # return np.array(output)
    return output

# Test the function
input_mat = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
    # [17, 18, 19, 20]
])
kern = np.array([
    [1, 0],
    [0, -1]
    # [1, 1]
])
result = convolution2d(input_mat, kern, stride=1)
result

# Test the function
# result_simple = convolution2d(input_mat, kern, stride=2)
# result_simple


In [ ]:
Let's break down how the convolution2d function works:

We start by determining the dimensions of both the input matrix and the kernel.
The dimensions of the output matrix are computed based on the size of the input matrix, the size of the kernel, and the stride.
We initialize an output matrix filled with zeros of the computed dimensions.
We slide the kernel over the input matrix, using the specified stride. For each position of the kernel, we calculate the element-wise product between the sub-matrix of the input (covered by the kernel) and the kernel itself. The sum of these products gives the value at the corresponding position in the output matrix.
Once we've iterated over the entire input matrix, we return the populated output matrix.

In [ ]:
import numpy as np

def convolution2d(input_matrix: np.ndarray, kernel: np.ndarray, stride: int = 1) -> np.ndarray:
    if stride <= 0 or not isinstance(stride, int):
        raise ValueError("Stride must be a positive integer.")

    if not isinstance(input_matrix, np.ndarray) or input_matrix.ndim != 2 or not isinstance(kernel, np.ndarray) or kernel.ndim != 2:
        raise TypeError("input_matrix and kernel must 2D np.ndarray.")
    
    # Get the dimensions of the input matrix and kernel
    input_rows = len(input_matrix)
    input_cols = len(input_matrix[0])
    kernel_rows = len(kernel)
    kernel_cols = len(kernel[0])
    
    # input_rows, input_cols = input_matrix.shape
    # kernel_rows, kernel_cols = kernel.shape
    
    # Compute the dimensions of the output matrix
    output_rows = (input_rows - kernel_rows) // stride + 1
    output_cols = (input_cols - kernel_cols) // stride + 1
    
    # Create an empty output matrix with zeros
    output_matrix = np.zeros((output_rows, output_cols))
        
    # Slide the kernel over the input matrix and compute the cross-correlation
    for i in range(output_rows):
        for j in range(output_cols):
            sum_val = 0
            for x in range(kernel_rows):
                for y in range(kernel_cols):
                    # Print the current element of input_matrix and kernel being multiplied
                    print(f"input_matrix[{i*stride + x}][{j*stride + y}] ({input_matrix[i*stride + x][j*stride + y]}) * kernel[{x}][{y}] ({kernel[x][y]})")
                    
                    sum_val += input_matrix[i*stride + x][j*stride + y] * kernel[x][y]
            
            # Print the calculated sum for the current position in the output matrix
            print(f"\nSum for output_matrix[{i}][{j}] = {sum_val}\n{'='*30}\n")
            output_matrix[i][j] = sum_val
    
    return np.array(output_matrix)

# Test the function
input_mat = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
kern = np.array([
    [1, 0],
    [0, -1]
])
result = convolution2d(input_mat, kern, stride=2)
print(result)
