# Examples

In [1]:
from src.main import convolution2d, window1d, transpose2d, create_random_matrix
import numpy as np
# from src import main

random_matrix = create_random_matrix(3, 4)

print(random_matrix)

input_matrix = [
    [1, 2],
    [4, 5],
    [2, 15]
  ]

print(transpose2d(input_matrix=random_matrix))
print(transpose2d(input_matrix=input_matrix))



[[1, 9, 1, 10], [2, 4, 9, 0], [9, 4, 0, 6]]
[[1, 2, 9], [9, 4, 4], [1, 9, 0], [10, 0, 6]]
[[1, 4, 2], [2, 5, 15]]


In [2]:
input_array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# input_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

windowed = window1d(input_array=input_array, size=2, shift=2, stride=2)
windowed



[[1, 3], [3, 5], [5, 7], [7, 9]]

In [3]:
windowed = window1d(list(range(10)), size=2, shift=2, stride=2)
# windowed = window1d(range(10), size=2, shift=2, stride=2)
windowed

[[0, 2], [2, 4], [4, 6], [6, 8]]

In [4]:
input_matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
kernel = np.array([
    [1, 0],
    [0, 1]
])
convolved = convolution2d(input_matrix=input_matrix, kernel=kernel, stride=2)
convolved

array([[ 7., 11.],
       [23., 27.]])

In [5]:
test_input_matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
test_kernel = np.array([[1, 0], [1, 0]])
test_stride = 2
convolved_output = convolution2d(test_input_matrix, test_kernel, test_stride)
convolved_output


array([[ 6., 10.],
       [22., 26.]])

# Matrix Transpose

In [7]:
def create_empty_matrix(shape = (4, 4)):
  rows = shape[0]
  cols = shape[1]
  matrix = []
  for i in range(rows):
    matrix.append([0 for i in range(cols)])
  return matrix

def transpose_without_numpy(matrix):
  '''it returns transpose of a matrix without any use of numpy'''
  #get shape of matrix
  rows = len(matrix)
  cols = len(matrix[0])
  
  #create empty matrix with shape = (cols, rows)
  transpose = []
  for _ in range(cols):
    transpose.append([0 for _ in range(rows)])
  
  # use basic formula for transpose which is B_i_j = A_i_j
  for n in range(len(matrix[0])):
    for n2 in range(len(matrix)):
      transpose[n][n2] = matrix[n2][n]
  
  return transpose

input_matrix = [
    [1, 2],
    [4, 5],
    [2, 15]
  ]

# input_matrix = [
#     [1.0, 2.0, 3.0],
#     [4.0, 5.0, 6.0],
#     [7.0, 8.0, 9.0]
# ]

# Transpose the matrix and display the result
transposed_matrix = transpose_without_numpy(input_matrix)
transposed_matrix

[[1, 4, 2], [2, 5, 15]]

In [11]:
from typing import List

def transpose2d(input_matrix: List[List[float]]) -> List[List[float]]:
    # Transpose the matrix
    return [[row[i] for row in input_matrix] for i in range(len(input_matrix[0]))]
  
# Example matrix
# input_matrix = [
#     [1.0, 2.0, 3.0],
#     [4.0, 5.0, 6.0],
#     [7.0, 8.0, 9.0]
# ]

# input_matrix = [
#     [1, 2, 3],
#     [4, 5, 6]
#   ]

input_matrix = [
    [1, 2],
    [4, 5],
    [2, 15]
  ]

# Transpose the matrix and display the result
transposed_matrix = transpose2d(input_matrix)
transposed_matrix


[[1, 4, 2], [2, 5, 15]]

In [1]:
# Outer List Comprehension, loop iterates over each column index in the original matrix. If the original matrix has 3 columns, it will loop 3 times. 
# Each iteration produces one row for the transposed matrix.
input_matrix = [
    [1, 2, 3],
    [4, 5, 6]
  ]

print(input_matrix[0])
print(len(input_matrix))
print(len(input_matrix[0]))

# for i in range(len(input_matrix[0])):
  # print(input_matrix[i])

# Inner List Comprehension: For every column index i from the outer loop, this loop iterates over each row of the original matrix and extracts the i-th element (column). This essentially takes all elements from the same column of the original matrix and puts them into a new row for the transposed matrix.
# print([row[i] for row in input_matrix])
for i in range(len(input_matrix[0])):
  print([row[i] for row in input_matrix])

[1, 2, 3]
2
3
[1, 4]
[2, 5]
[3, 6]


In [31]:
from typing import List

def transpose2d_with_args(input_matrix: List[float]) -> List[List[float]]:
    return [list(row) for row in zip(*input_matrix)]
    # return [row for row in zip(*input_matrix)]

# Example usage
input_matrix = [
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0]
]

transposed_matrix_args = transpose2d_with_args(input_matrix)
transposed_matrix_args


[[1.0, 4.0, 7.0], [2.0, 5.0, 8.0], [3.0, 6.0, 9.0]]

In [25]:
import random

def create_random_matrix(rows: int, columns: int) -> List[List[float]]:
    """Create a matrix filled with random numbers between 0 to 10 with a defined shape."""
    return [[random.randint(0, 10) for column in range(columns)] 
              for row in range(rows)]

# Example usage: Create a 3x4 matrix filled with random numbers between 0 to 10
random_matrix = create_random_matrix(3, 4)
random_matrix


[[4, 2, 4, 2], [10, 3, 9, 2], [0, 2, 2, 0]]

In [33]:
def transpose2d(input_matrix: List[List[float]]) -> List[List[float]]:
    """
    Transpose a 2D matrix using Python standard library.

    This function takes a 2D list (matrix) as input and returns its transpose.
    The transpose of a matrix is obtained by swapping rows with columns.

    Args:
    - input_matrix (List[List[float]]): The input 2D list (matrix) to be transposed.

    Returns:
    - List[List[float]]: The transposed matrix.

    Example:
    >>> transpose2d_simple([[1, 2], [3, 4], [5, 6]])
    [[1, 3, 5], [2, 4, 6]]
    """
    rows = len(input_matrix)
    columns = len(input_matrix[0])

    # Instantiate an empty matrix
    transpose = []
    for _ in range(columns):
        transpose.append([0] * rows)

    # Fill empty matrix with transposed elements using nested loops
    try:
        for row in range(rows):
            for col in range(columns):
                transpose[col][row] = input_matrix[row][col]
        return transpose
    except Exception as e:
        print("Error in transposition operation:", str(e))
        return None
      
# random_matrix = create_random_matrix(3, 4)
random_matrix = [[2, 6, 6, 5], 
                 [6, 0, 8, 5], 
                 [3, 3, 9, 9]]

transposed_matrix = transpose2d(random_matrix)
transposed_matrix

[[2, 6, 3], [6, 0, 3], [6, 8, 9], [5, 5, 9]]

In [12]:
# input_matrix = [
#     [1, 2, 3], 
#     [4, 5, 6], 
#     [7, 8, 9]
# ]

input_matrix = [
    [1, 2], 
    [4, 5], 
    [7, 8]
]

list(zip(*input_matrix))

# zip(*input_matrix) # <zip at 0x7fed20f82fc0>
# map(list, zip(*input_matrix)) # <map at 0x7fed003a0bb0>
# list(map(list, zip(*input_matrix)))

[(1, 4, 7), (2, 5, 8)]

In [ ]:
The input_matrix should be a 2D list of floats.
The function uses the zip(*input_matrix) expression to perform the transpose operation.
The rows of the input_matrix become the columns of the transposed matrix, and vice versa.
The resulting transposed matrix has dimensions (number of columns, number of rows) compared to the input matrix.
The function returns the transposed matrix as a 2D list of floats.


transpose function that works on matrices (2d tensors) and has this signature: transpose2d(input_matrix: list[list[float]]) -> list, where input_matrix is a list of lists of real numbers.



In [15]:
import numpy as np
# Showcase of some important NumPy functions

# 1. Creating Arrays:
arr_from_list = np.array([1, 2, 3, 4, 5])
zeros_arr = np.zeros((2, 2))
ones_arr = np.ones((3, 3))
sequence_arr = np.arange(10)
linspace_arr = np.linspace(0, 1, 5)

# 2. Array Operations:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
elementwise_product = a * b
matrix_product = a @ b

# 3. Mathematical Functions:
sin_values = np.sin(np.array([0, np.pi/2, np.pi]))

# 4. Random Module:
random_numbers = np.random.rand(5)
random_integers = np.random.randint(1, 10, size=5)

# Display the results
arr_from_list, zeros_arr, ones_arr, sequence_arr, linspace_arr, elementwise_product, matrix_product, sin_values, random_numbers, random_integers



(array([1, 2, 3, 4, 5]),
 array([[0., 0.],
        [0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([ 4, 10, 18]),
 32,
 array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16]),
 array([0.96380511, 0.96672175, 0.38667587, 0.96408699, 0.83195417]),
 array([1, 2, 7, 5, 3]))

In [67]:
from typing import TypeVar, List
import numpy as np

# Create a custom type variable for List[List[float]]
Matrix = TypeVar('Matrix', bound=List[List[float]])

def transpose2d(input_matrix: Matrix) -> Matrix:
    """
    Transpose a 2D matrix using Python standard library, by swapping rows with columns.

    Parameters:
    - input_matrix (Matrix): The input is a 2D list of floats.

    Returns:
    - Matrix: The transposed matrix as a 2D list of floats.

    Raises:
    - Exception: If an error in matrix transposition occurs.

    Example use:

    transpose2d([[1, 2], [3, 4], [5, 6]])
    [[1, 3, 5], [2, 4, 6]]

    """
    rows = len(input_matrix)
    columns = len(input_matrix[0])

    transpose = []
    for _ in range(columns):
        transpose.append([0] * rows)

    # Fill empty matrix with transposed elements using nested loops
    try:
        for row in range(rows):
            for col in range(columns):
                transpose[col][row] = input_matrix[row][col]
        return transpose
    except Exception as e:
        print("Error in transposition operation:", str(e))
        return None

# Test
# print(transpose2d(np.array([[1, 2], [3, 4], [5, 6]])))

# random_matrix = [[2, 6, 6, 5], 
#                  [6, 0, 8, 5], 
#                  [3, 3, 9, 9]]

random_matrix = ([[1, 2], [3, 4], [5, 6]])

transposed_matrix = transpose2d(random_matrix)
transposed_matrix

[[1, 3, 5], [2, 4, 6]]

# Windowing

In [4]:
import numpy as np
from typing import Union, List

In [5]:
import numpy as np
from typing import Union

def window1d(input_array: Union[List[float], np.ndarray], size: int, shift: int = 1, stride: int = 1) -> Union[List[List[float]], List[np.ndarray]]:
    """Generate windowed data from a 1D array or list."""
    # Initialize an empty list to hold the windowed data
    windows = []
    
    # Define the start and end indices for windowing
    start_idx = 0
    end_idx = size * stride
    
    # Loop until the end index goes out of bounds
    while end_idx <= len(input_array):
        # Extract the window using slicing and stride
        window = input_array[start_idx:end_idx:stride]
        
        # If input is a numpy array, keep the type consistent
        if isinstance(input_array, np.ndarray):
            windows.append(window)
        else:
            windows.append(list(window))
        
        # Update the start and end indices based on the shift
        start_idx += shift
        end_idx += shift
        
    # first handle all as list, and do conversion and type check at the end
    # tolist()
    

    return windows

# Test the function
# test_array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
test_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
type(test_array)

windowed_data = window1d(test_array, size=3, shift=2, stride=2)
windowed_data


[array([1, 3, 5]), array([3, 5, 7]), array([5, 7, 9])]

In [8]:
# Trial
def window1d(*, input_array: Union[List[float], np.ndarray], size: int, shift: int = 1, stride: int = 1) -> Union[List[List[float]], List[np.ndarray]]:
    """Generate windowed data from a 1D array or list using a double loop.
    Parameters:
    - input_array: The input 1D array or list.
    - size: The size of each window, number of observations per window
    - shift: The step size between different windows.
    - stride: The step size within each window.
    
    Returns:
    - A list of windowed data.
    """
    # Initialize an empty list to hold the windowed data
    windows = []
    
    # Starting index for the outer loop
    i = 0
    
    # Continue until the end of the array is reached
    while i + size * stride <= len(input_array):
        # Initialize an empty list to hold the current window
        window = []
        
        # Starting Stride index for the inner loop
        j = 0
        
        # Extract data for the current window considering the stride
        while len(window) < size and (i + j) < len(input_array):
            window.append(input_array[i + j])
            j += stride
        
        # If the window size is as expected, append it to the windows list
        if len(window) == size:
            if isinstance(input_array, np.ndarray):
                windows.append(np.array(window))
            else:
                windows.append(window)
        
        # Shift to the next window using the shift provided
        i += shift
        
    return windows

# test_array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
new_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
type(new_array)

windowed_data = window1d(input_array=new_array, size=3, shift=2, stride=2)
windowed_data


[array([1, 3, 5]), array([3, 5, 7]), array([5, 7, 9])]

In [19]:
input_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
size = 3
stride = 2
shift = 2

num_windows = (len(input_array) - size * stride) // shift + 1
#                           10 - 3 * 2 // 2 + 1
print(len(input_array))
print(num_windows)

print(input_array[0:10:2])

10
3
[1 3 5 7 9]


In [21]:
# FINAL
def window1d(input_array: Union[List[float], np.ndarray], size: int, shift: int = 1, stride: int = 1) -> Union[List[List[float]], List[np.ndarray]]:
    """Generate windowed data from a 1D array or list using slicing.
    
    Parameters:
    - input_array: 1D np.array or list.
    - size: The size of returned window, number of objects per window.
    - shift: The step size between different windows.
    - stride: The step size within each window.
    
    Returns:
    - A list of lists or arrays of windowed data, depending on input type.
    
    Example use:
    
    """
    
    # Ensure inputs size, shift, and stride are positive
    if size <= 0 or shift <= 0 or stride <= 0:
        raise ValueError("One of the parameters 'size', 'shift', 'stride' is not positive.")
    
    windows = []
    
    # Get the number of times to loop through, in int
    num_loops = (len(input_array) - size * stride) // shift + 1
    
    # Loop through to extract each window
    # for i in range(0, len(input_array) - size + 1, shift):
    for i in range(num_loops):
        
        # Get and increment start and end indices
        start = i * shift # Always starts at 0
        end = start + size * stride
        
        # Use slicing and stride to extract array
        window = input_array[start:end:stride]
        
        # Keeping type consistent with checks
        # if isinstance(input_array, np.ndarray):
        #         windows.append(np.array(window))
        # else:
        #     windows.append(list(window))
        
        # Slice generally retains the object Type, and these are append-able, hence no type strict type check is necessary
        windows.append(window)
        
    return windows

# Test the function
# test_array_np = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# test_array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
test_array = [16, 14,  9, 10,  5,  2,  6, 19, 16,  1, 12,  3,  5, 19,  3, 11, 10, 5,  1, 17]
# test_array = np.random.randint(0, 20, 20)
test_array
windowed_data_slicing = window1d(test_array, size=3, shift=2, stride=2)
windowed_data_slicing

new_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
type(new_array)

windowed_data = window1d(input_array=new_array, size=3, shift=2, stride=2)
windowed_data


[array([1, 3, 5]), array([3, 5, 7]), array([5, 7, 9])]

# Convolution and Cross correlation

In [62]:
import numpy as np

def convolution2d(input_matrix: np.ndarray, kernel: np.ndarray, stride: int = 1) -> np.ndarray:
    """
    Compute the 2D cross-correlation between the input matrix and kernel, by sliding the kernel over the input matrix and computing the sum of element-wise products at each position.
    The positions where the input_matrix and the kernel cannot fully overlap are excluded from the output.
    
    Parameters:
    - input_matrix (np.ndarray): 2D numpy array input matrix.
    - kernel (np.ndarray): 2D numpy array convolution kernel.
    - stride (int, optional): Integer representing the stride of the convolution operation. Default is 1.
    
    Returns:
    - np.ndarray: 2D numpy array representing the result of the cross-correlation operation.

    Raises:
    - ValueError: If stride is not a positive integer.
    - TypeError: If input_matrix or kernel is not a 2D np.ndarray.
    - ValueError: If kernel dimensions are bigger than input_matrix dimensions.
    
    Example use:
        >>> input_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
        >>> kernel = np.array([[0, 1], [1, 0]])
        >>> stride = 1
        >>> result = convolution2d(input_matrix, kernel, stride)
        >>> print(result)
        [[13. 18.]
        [24. 29.]]
    
    """

    # Ensure inputs size, shift, and stride are positive
    if stride <= 0 or not isinstance(stride, int):
        raise ValueError("Stride must be a positive integer.")
    
    # Ensure inputs are 2D arrays
    if not isinstance(input_matrix, np.ndarray) or input_matrix.ndim != 2 or not isinstance(kernel, np.ndarray) or kernel.ndim != 2:
        raise TypeError("input_matrix and kernel must 2D np.ndarray.")
    
    input_rows, input_cols = input_matrix.shape
    kernel_rows, kernel_cols = kernel.shape

    # Ensure matrix and kernel shapes are compatible
    if input_rows <= kernel_rows or input_cols <= kernel_cols:
        raise ValueError("Input matrix dimensions must be greater or equal to kernel dimensions.")
    
    output_rows = (input_rows - kernel_rows) // stride + 1
    output_cols = (input_cols - kernel_cols) // stride + 1
    
    # Create an empty output matrix with zeros
    output = np.zeros((output_rows, output_cols))
    
    # Slide the kernel over the input matrix and compute the cross-correlation
    for i in range(output_rows):
        for j in range(output_cols):
            sum_val = 0
            for x in range(kernel_rows):
                for y in range(kernel_cols):
                    # sum_val += input_matrix[i*stride + x][j*stride + y] * kernel[x][y]
                    matrix = input_matrix[i*stride + x][j*stride + y]
                    sum_val += matrix * kernel[x][y]
            output[i][j] = sum_val
            
            
    # for i in range(0, output_rows):
    #     for j in range(0, output_cols):
    #         output_matrix[i, j] = np.sum(input_matrix[i*stride:i*stride+kernel_rows, j*stride:j*stride+kernel_cols] * kernel)
            
    
    # return np.array(output)
    return output

# Test the function
input_mat = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
    # [17, 18, 19, 20]
])
kern = np.array([
    [1, 0],
    [0, -1]
    # [1, 1]
])
result = convolution2d(input_mat, kern, stride=1)
result

# Test the function
# result_simple = convolution2d(input_mat, kern, stride=2)
# result_simple


array([[-5., -5., -5.],
       [-5., -5., -5.],
       [-5., -5., -5.]])

In [ ]:
Let's break down how the convolution2d function works:

We start by determining the dimensions of both the input matrix and the kernel.
The dimensions of the output matrix are computed based on the size of the input matrix, the size of the kernel, and the stride.
We initialize an output matrix filled with zeros of the computed dimensions.
We slide the kernel over the input matrix, using the specified stride. For each position of the kernel, we calculate the element-wise product between the sub-matrix of the input (covered by the kernel) and the kernel itself. The sum of these products gives the value at the corresponding position in the output matrix.
Once we've iterated over the entire input matrix, we return the populated output matrix.

In [39]:
import numpy as np

def convolution2d(input_matrix: np.ndarray, kernel: np.ndarray, stride: int = 1) -> np.ndarray:
    if stride <= 0 or not isinstance(stride, int):
        raise ValueError("Stride must be a positive integer.")

    if not isinstance(input_matrix, np.ndarray) or input_matrix.ndim != 2 or not isinstance(kernel, np.ndarray) or kernel.ndim != 2:
        raise TypeError("input_matrix and kernel must 2D np.ndarray.")
    
    # Get the dimensions of the input matrix and kernel
    input_rows = len(input_matrix)
    input_cols = len(input_matrix[0])
    kernel_rows = len(kernel)
    kernel_cols = len(kernel[0])
    
    # input_rows, input_cols = input_matrix.shape
    # kernel_rows, kernel_cols = kernel.shape
    
    # Compute the dimensions of the output matrix
    output_rows = (input_rows - kernel_rows) // stride + 1
    output_cols = (input_cols - kernel_cols) // stride + 1
    
    # Create an empty output matrix with zeros
    output_matrix = np.zeros((output_rows, output_cols))
        
    # Slide the kernel over the input matrix and compute the cross-correlation
    for i in range(output_rows):
        for j in range(output_cols):
            sum_val = 0
            for x in range(kernel_rows):
                for y in range(kernel_cols):
                    # Print the current element of input_matrix and kernel being multiplied
                    print(f"input_matrix[{i*stride + x}][{j*stride + y}] ({input_matrix[i*stride + x][j*stride + y]}) * kernel[{x}][{y}] ({kernel[x][y]})")
                    
                    sum_val += input_matrix[i*stride + x][j*stride + y] * kernel[x][y]
            
            # Print the calculated sum for the current position in the output matrix
            print(f"\nSum for output_matrix[{i}][{j}] = {sum_val}\n{'='*30}\n")
            output_matrix[i][j] = sum_val
    
    return np.array(output_matrix)

# Test the function
input_mat = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
kern = np.array([
    [1, 0],
    [0, -1]
])
result = convolution2d(input_mat, kern, stride=2)
print(result)


input_matrix[0][0] (1) * kernel[0][0] (1)
input_matrix[0][1] (2) * kernel[0][1] (0)
input_matrix[1][0] (5) * kernel[1][0] (0)
input_matrix[1][1] (6) * kernel[1][1] (-1)

Sum for output_matrix[0][0] = -5

input_matrix[0][2] (3) * kernel[0][0] (1)
input_matrix[0][3] (4) * kernel[0][1] (0)
input_matrix[1][2] (7) * kernel[1][0] (0)
input_matrix[1][3] (8) * kernel[1][1] (-1)

Sum for output_matrix[0][1] = -5

input_matrix[2][0] (9) * kernel[0][0] (1)
input_matrix[2][1] (10) * kernel[0][1] (0)
input_matrix[3][0] (13) * kernel[1][0] (0)
input_matrix[3][1] (14) * kernel[1][1] (-1)

Sum for output_matrix[1][0] = -5

input_matrix[2][2] (11) * kernel[0][0] (1)
input_matrix[2][3] (12) * kernel[0][1] (0)
input_matrix[3][2] (15) * kernel[1][0] (0)
input_matrix[3][3] (16) * kernel[1][1] (-1)

Sum for output_matrix[1][1] = -5

[[-5. -5.]
 [-5. -5.]]
