In [5]:
my_list = [[1, 2, 3], [40, 50, 60], [9, 8, 7]]

import numpy as np
my_array = np.array(my_list)
my_array[:,1]
# np.sum(my_array[:, 1])


array([ 2, 50,  8])

In [ ]:
class Cage(object):
  
  
  def __init__(self, id_number: int):
    self.id_number = id_number
    self.animals = []
    
  def add_animals(self, *animals: str):
    self.animals = animals.extend(*animals)
    
    
  def __repr__(self) str:
    print(self.id_number, self.animals)

In [8]:
class Animal():
    def __init__(self, color, number_of_legs):
        self.species = self.__class__.__name__
        self.color = color
        self.number_of_legs = number_of_legs

    def __repr__(self):
        return f'{self.color} {self.species}, {self.number_of_legs} legs'

class Wolf(Animal):
    def __init__(self, color):
        super().__init__(color, 4)
 

class Sheep(Animal):
    def __init__(self, color):
        super().__init__(color, 4)
 

class Snake(Animal):
    def __init__(self, color):
        super().__init__(color, 0)
 

class Parrot(Animal):
    def __init__(self, color):
        super().__init__(color, 2)
 

class Cage():
    def __init__(self, id_number):
        self.id_number = id_number
        self.animals = []
 
    def add_animals(self, *animals):
        for one_animal in animals:
            self.animals.append(one_animal)
 
    def __repr__(self):
        output = f'Cage {self.id_number}\n'
        output += '\n'.join('\t' + str(animal)
                            for animal in self.animals)
        return output
     
wolf = Wolf('black')
sheep = Sheep('white')
snake = Snake('brown')
parrot = Parrot('green')
 
c1 = Cage(1)
c1.add_animals(wolf, sheep)
 
c2 = Cage(2)
c2.add_animals(snake, parrot)
 
print(c1)
print(c2)


Cage 1
	black Wolf, 4 legs
	white Sheep, 4 legs
Cage 2
	brown Snake, 0 legs
	green Parrot, 2 legs


In [21]:
# invariant.py
from typing import TypeVar, Generic

class Beverage:  
    """Any beverage."""

class Juice(Beverage):
    """Any fruit juice."""

class OrangeJuice(Juice):
    """Delicious juice from Brazilian oranges."""

T = TypeVar('T')  

class BeverageDispenser(Generic[T]):  
    """A dispenser parameterized on the beverage type."""
    def __init__(self, beverage: T) -> None:
        self.beverage = beverage

    def dispense(self) -> T:
        return self.beverage

def install(dispenser: BeverageDispenser[Juice]) -> None:  
    """Install a fruit juice dispenser."""
    print(f"{__name__} successfully installed")

In [22]:
juice_dispenser = BeverageDispenser(Juice())
install(juice_dispenser)
# juice_dispenser

__main__successfully installed


In [23]:
beverage_dispenser = BeverageDispenser(Beverage())
install(beverage_dispenser)
## mypy: Argument 1 to "install" has
## incompatible type "BeverageDispenser[Beverage]"
##          expected "BeverageDispenser[Juice]"

__main__successfully installed


Basic Python Functions:

Input/Output: input(), print()
Type conversion: int(), float(), str(), list(), set(), tuple()
String functions: split(), join(), replace(), startswith(), endswith(), strip(), lower(), upper()
List methods: append(), extend(), remove(), pop(), index(), count(), sort(), reverse()
Data Structures:

Lists: List comprehensions, slicing
Sets: add(), remove(), union(), intersection(), difference()
Dictionaries: keys(), values(), items(), dictionary comprehensions
Stacks and Queues: Can be implemented using lists or collections.deque
Tuples: Immutable sequences
Control Flow:

Conditional statements: if, elif, else
Loops: for, while
Loop control: break, continue, pass
Python Libraries:

math: Common mathematical functions. E.g., sqrt(), factorial(), gcd(), ceil(), floor()
itertools: Iterators for efficient looping. E.g., permutations(), combinations(), groupby(), cycle()
collections: Useful extensions of common data structures. E.g., Counter, defaultdict, deque, namedtuple
re: Regular expressions for string operations
string: Common string operations and constants
Advanced:

List comprehensions with conditions
Lambda functions
map(), filter(), reduce()
Generators and the yield keyword
Algorithms and Problem-solving:

Sorting algorithms
Searching algorithms: Linear search, binary search
Basic graph algorithms: Breadth-first search (BFS), Depth-first search (DFS)
Dynamic programming basics
Recursion
File I/O (occasionally required):

open(), read(), write(), close()
Error and Exception Handling:

try, except, finally
Object-Oriented Programming:

Classes, objects, inheritance, polymorphism

# List Comprehension

In [1]:
squares = [x**2 for x in range(10)]
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [3]:
evens = [x for x in range(10) if x % 2 == 0]
evens

[0, 2, 4, 6, 8]

In [5]:
celsius = [0, 10, 20, 30]
fahrenheit = [(9/5)*temp + 32 for temp in celsius]
print(fahrenheit)  # [32.0, 50.0, 68.0, 86.0]


[32.0, 50.0, 68.0, 86.0]


# Iterator
An iterator is an object that contains a countable number of values and can be iterated upon using the next() function.

In [6]:
my_string = "Hello"
itr = iter(my_string)
print(next(itr))  # H
print(next(itr))  # e


H
e


In [7]:
my_list = [1, 2, 3]
itr = iter(my_list)
print(next(itr))  # 1
print(next(itr))  # 2


1
2


# Generator
Generators are a simple way of creating iterators using functions and the yield keyword.

In [11]:
def even_gen(n):
    for i in range(n):
        if i % 2 == 0:
            yield i

evens = even_gen(10)
print(next(evens))  # 0
print(next(evens))  # 2
print(list(evens))


0
2
[4, 6, 8]


In [23]:
def fibonacci(n):
    a, b = 0, 1
    for _ in range(n):
        yield a
        a, b = b, a + b

fib = fibonacci(5)
for num in fib:
    print(num)


0
1
1
2
3


# Lambda Functions
A lambda function is a small anonymous function. It can have any number of arguments but can only have one expression.

In [24]:
add = lambda x, y: x + y
print(add(3, 4))  # 7


7


In [25]:
square = lambda x: x**2
print(square(5))  # 25

25


In [26]:
is_even = lambda x: x % 2 == 0
print(is_even(4))  # True
print(is_even(7))  # False


True
False


In [ ]:
numbers = [1, 2, 3, 4]
squared_numbers = [(lambda x: x**2)(num) for num in numbers]
print(squared_numbers)  # [1, 4, 9, 16]


In [40]:
numbers = [1, 2, 3, 4]
even_numbers = [num for num in numbers if (lambda x: x % 2 == 0)(num)]
print(even_numbers)  # [2, 4]


[2, 4]


In [42]:
words = ["apple", "banana", "cherry"]
capitalized_words = [(lambda x: x.capitalize())(word) for word in words]
# Same as: 
# capitalized_words = [word.capitalize() for word in words]
print(capitalized_words)  # ['Apple', 'Banana', 'Cherry']


['Apple', 'Banana', 'Cherry']


# Counter
A Counter is a dictionary subclass that counts hashable objects. It's an unordered collection where elements are stored as dictionary keys and their counts as dictionary values.

In [27]:
from collections import Counter

count = Counter("aabbcc")
print(count)  # Counter({'a': 2, 'b': 2, 'c': 2})


Counter({'a': 2, 'b': 2, 'c': 2})


In [28]:
sentence = "apple banana apple orange"
words = sentence.split()
count = Counter(words)
print(count)  # Counter({'apple': 2, 'banana': 1, 'orange': 1})


Counter({'apple': 2, 'banana': 1, 'orange': 1})


In [29]:
c1 = Counter(a=3, b=2, c=1)
c2 = Counter(a=1, b=2, c=3)
result = c1 - c2
print(result)  # Counter({'a': 2})


Counter({'a': 2})


# defaultdict
A defaultdict is a dictionary subclass that provides a default value for the key that does not exist.

In [31]:
from collections import defaultdict

int_dict = defaultdict(int)
int_dict["a"] += 1
print(int_dict["a"])  # 1
print(int_dict["b"])  # 0 (default int value)


1
0


In [32]:
items = [("apple", 3), ("banana", 2), ("apple", 5)]
fruit_dict = defaultdict(list)
for fruit, count in items:
    fruit_dict[fruit].append(count)
print(fruit_dict)  # defaultdict(<class 'list'>, {'apple': [3, 5], 'banana': [2]})


defaultdict(<class 'list'>, {'apple': [3, 5], 'banana': [2]})


In [33]:
str_dict = defaultdict(str)
str_dict["a"] += "hello"
print(str_dict["a"])  # "hello"
print(str_dict["b"])  # "" (default str value)


hello



# deque
A deque (double-ended queue) is an ordered collection of items similar to a list, but it supports adding and removing elements from both ends in O(1) time.

In [34]:
from collections import deque

d = deque()
d.append(1)         # deque([1])
d.appendleft(2)     # deque([2, 1])
d.pop()             # Returns 1, deque becomes [2]
d.popleft()         # Returns 2, deque becomes []


2

In [37]:
d = deque([1, 2, 3, 4, 5])
d.rotate(2)         # deque([4, 5, 1, 2, 3])
print(d)
d.rotate(-2)        # deque([1, 2, 3, 4, 5])
print(d)

deque([4, 5, 1, 2, 3])
deque([1, 2, 3, 4, 5])


In [39]:
d = deque(maxlen=3)  # Only hold 3 items
d.append(1)          # deque([1])
d.append(2)          # deque([1, 2])
d.append(3)          # deque([1, 2, 3])
d.append(4)          # deque([2, 3, 4])
d


deque([2, 3, 4], maxlen=3)

# enumerate
The enumerate function returns an iterator that produces tuples containing the index and the value from the original iterable.

In [51]:
letters = ['a', 'b', 'c', 'd', 'e', 'f']

for idx, letter in enumerate(letters, start=1):
    print(idx, letter)

1 a
2 b
3 c
4 d
5 e
6 f


In [52]:
enume = list(enumerate(letters))
enume

[(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd'), (4, 'e'), (5, 'f')]

In [53]:
letter_dict = dict(enumerate(letters))
print(letter_dict)  # {0: 'a', 1: 'b', 2: 'c'}


{0: 'a', 1: 'b', 2: 'c', 3: 'd', 4: 'e', 5: 'f'}


# zip
The zip function returns an iterator of tuples, where the first item in each passed iterable is paired together, then the second item in each passed iterable is paired together, and so on.



In [56]:
names = ['Alice', 'Bob']
scores = [85, 90]
paired = list(zip(names, scores))
print(paired)  # [('Alice', 85), ('Bob', 90)]


[('Alice', 85), ('Bob', 90)]


In [57]:
# Pairing lists of different lengths:
names = ['Alice', 'Bob', 'Charlie']
scores = [85, 90]
paired = list(zip(names, scores))
print(paired)  # [('Alice', 85), ('Bob', 90)]


[('Alice', 85), ('Bob', 90)]


In [58]:
# Unzipping
paired = [('Alice', 85), ('Bob', 90)]
names, scores = zip(*paired)
print(names)  # ('Alice', 'Bob')
print(scores)  # (85, 90)


('Alice', 'Bob')
(85, 90)


## Alternative unzips:

In [62]:
names = []
scores = []
for name, score in paired:
  names.append(name)
  scores.append(score)
print(names)
print(scores)

['Alice', 'Bob']
[85, 90]


In [64]:
from operator import itemgetter

paired = [('Alice', 85), ('Bob', 90)]
names = list(map(itemgetter(0), paired))
scores = list(map(itemgetter(1), paired))
print(names)
print(scores)


['Alice', 'Bob']
[85, 90]


In [68]:
paired = [('Alice', 85), ('Bob', 90)]
names = [name for name, _ in paired]
scores = [score for _, score in paired]
print(names)
print(scores)

['Alice', 'Bob']
[85, 90]


# map:
The map function applies a given function to all items in the input list.

In [71]:
numbers = [1, 2, 3, 4]
squared = list(map(lambda x: x**2, numbers))
print(squared)  # [1, 4, 9, 16]

[1, 4, 9, 16]


In [73]:
str_numbers = ["1", "2", "3"]
numbers = list(map(int, str_numbers))
print(numbers)  # [1, 2, 3]

[1, 2, 3]


In [75]:
words = ["apple", "banana", "cherry"]
lengths = list(map(len, words))
print(lengths)  # [5, 6, 6]
print(len(words))


[5, 6, 6]
3


# Using zip with map:
Suppose you want to add two lists element-wise:

In [78]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
result = list(map(lambda pair: pair[0] + pair[1], zip(list1, list2)))
print(result)  # [5, 7, 9]
result2 = list(zip(list1, list2))
print(result2)

[5, 7, 9]
[(1, 4), (2, 5), (3, 6)]


# Using list with map:
This simply converts the map object to a list:

In [80]:
numbers = [1, 2, 3, 4]
squared = list(map(lambda x: x**2, numbers))
print(squared)  # [1, 4, 9, 16]


[1, 4, 9, 16]


# Basic Type Conversion:


In [81]:
num_int = 5
num_float = float(num_int)
print(num_float)  # 5.0


5.0


In [83]:
import pandas as pd

df = pd.DataFrame({
    'int_column': [1, 2, 3],
    'float_column': [1.1, 2.2, 3.3],
    'str_column': ['one', 'two', 'three']
})

print(df)

df['int_column'] = df['int_column'].astype(float)
df['float_column'] = df['float_column'].astype(int)
df['str_column'] = df['str_column'].astype('category')

print(df)
print(df.dtypes)

   int_column  float_column str_column
0           1           1.1        one
1           2           2.2        two
2           3           3.3      three
   int_column  float_column str_column
0         1.0             1        one
1         2.0             2        two
2         3.0             3      three
int_column       float64
float_column       int64
str_column      category
dtype: object


In [88]:
df = pd.DataFrame({
    'int_column': [1, 2, 3],
    'float_column': [1.1, 2.2, 3.3],
    'str_column': ['one', 'two', 'three']
})

convert_dict = {
    'int_column': float,
    'float_column': int,
    'str_column': str
    # 'str_column': 'category'
}

df = df.astype(convert_dict)

print(df)
print(df.dtypes)


   int_column  float_column str_column
0         1.0             1        one
1         2.0             2        two
2         3.0             3      three
int_column      float64
float_column      int64
str_column       object
dtype: object


# Difference between for and while loops:
for loop:  
Iterates over a sequence (like a list, tuple, string, or range) or other iterable objects.  
Runs for a predetermined number of times, which is defined by the length of the sequence.  
while loop:  
Executes as long as a given condition remains True.  
Can potentially run indefinitely if the condition never becomes False.  


In [89]:
# For loop:
for i in range(3):
    print(i)
# Output:
# 0
# 1
# 2


0
1
2


In [90]:
# while loop:
count = 0
while count < 3:
    print(count)
    count += 1
# Output:
# 0
# 1
# 2


0
1
2


# Dictionaries:

In [92]:
# keys(): Returns a view object displaying a list of all the keys in the dictionary.
dict_example = {'a': 1, 'b': 2, 'c': 3}
print(dict_example.keys())  # dict_keys(['a', 'b', 'c'])

dict_keys(['a', 'b', 'c'])


In [93]:
# values():
# Returns a view object displaying a list of all the values in the dictionary.
dict_example = {'a': 1, 'b': 2, 'c': 3}
print(dict_example.values())  # dict_values([1, 2, 3])


dict_values([1, 2, 3])


In [94]:
# items():
# Returns a view object displaying a list of the dictionary's key-value tuple pairs.
dict_example = {'a': 1, 'b': 2, 'c': 3}
print(dict_example.items())  # dict_items([('a', 1), ('b', 2), ('c', 3)])


dict_items([('a', 1), ('b', 2), ('c', 3)])


In [95]:
# Dictionary comprehensions
squared_dict = {x: x**2 for x in range(1, 6)}
print(squared_dict)  # {1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [96]:
# create a dictionary from two lists:
keys = ['a', 'b', 'c']
values = [1, 2, 3]
dict_from_lists = {k: v for k, v in zip(keys, values)}
print(dict_from_lists)  # {'a': 1, 'b': 2, 'c': 3}


{'a': 1, 'b': 2, 'c': 3}


# Loop Control: break, continue, pass
break:  
* Terminates the current loop and resumes execution at the next statement after the loop.  

continue:  
* Causes the loop to skip the remainder of its body and immediately retest its condition prior to reiterating.  

pass:  
* A null operation; nothing happens when it executes. It's often used as a placeholder.

In [97]:
# Break
for i in range(5):
    if i == 3:
        break
    print(i)
# Output:
# 0
# 1
# 2


0
1
2


In [98]:
# continue
for i in range(5):
    if i == 3:
        continue
    print(i)
# Output:
# 0
# 1
# 2
# 4


0
1
2
4


In [99]:
# pass
for i in range(5):
    if i == 3:
        pass
    print(i)
# Output:
# 0
# 1
# 2
# 3
# 4


0
1
2
3
4


# itertools:
permutations():
* Returns all possible permutations of the elements of an iterable.  

combinations():
* Returns all possible combinations of the elements of an iterable, taking r elements at a time.  

groupby():
* Groups consecutive elements of an iterable that have the same value.  

cycle():
* Returns elements from an iterable and saves a copy of each. When the iterable is exhausted, returns elements from the saved copy.

In [100]:
from itertools import permutations

perms = list(permutations([1, 2, 3], 2))
print(perms)  # [(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)]

[(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)]


In [101]:
from itertools import combinations

combs = list(combinations([1, 2, 3], 2))
print(combs)  # [(1, 2), (1, 3), (2, 3)]


[(1, 2), (1, 3), (2, 3)]


In [104]:
from itertools import groupby

data = [1, 1, 2, 3, 3, 3]
for key, group in groupby(data):
    print(key, list(group))
# Output:
# 1 [1, 1]
# 2 [2]
# 3 [3, 3, 3]

1 [1, 1]
2 [2]
3 [3, 3, 3]
[(1, <itertools._grouper object at 0x147fac760>), (2, <itertools._grouper object at 0x147fac820>), (3, <itertools._grouper object at 0x147fadb10>)]


In [105]:
from itertools import cycle

c = cycle('AB')
print(next(c))  # A
print(next(c))  # B
print(next(c))  # A


A
B
A


# re - Regular Expressions:
Regular expressions provide a way to match strings of text, such as particular characters, words, or patterns of characters.

In [106]:
# Search for a pattern in a string:
import re

result = re.search(r'\d+', 'Hello 123 world')
print(result.group())  # 123


123


In [107]:
# Replace patterns in a string
result = re.sub(r'\d+', '456', 'Hello 123 world')
print(result)  # Hello 456 world


Hello 456 world


In [108]:
# Split string by pattern:
result = re.split(r'\s+', 'Hello   world')
print(result)  # ['Hello', 'world']


['Hello', 'world']


# File I/O 

In [ ]:
# Open a file for reading (default mode is 'r')
file = open("example.txt")

# Open a file for writing
file = open("example.txt", 'w')

# Open a file for appending
file = open("example.txt", 'a')

# Open a file for both reading and writing
file = open("example.txt", 'r+')


In [ ]:
# This function reads the content of a file.
file = open("example.txt", 'r')
content = file.read()
print(content)
file.close()


In [ ]:
# You can also specify the number of bytes you want to read
file = open("example.txt", 'r')
content = file.read(5)  # Reads the first 5 bytes
print(content)
file.close()


In [ ]:
# write()
# This function writes data to a file. If the file already contains data, the write function will overwrite it when used in 'w' mode.
file = open("example.txt", 'w')
file.write("Hello, World!")
file.close()
# Now, "example.txt" contains "Hello, World!"

In [ ]:
# close()
# This function closes an open file. It's a good practice to always close the file when you're done with it.
file = open("example.txt", 'r')
content = file.read()
print(content)
file.close()


Using the with statement (recommended for file operations):  
The with statement is used to wrap the execution of a block of code. It's especially useful for file operations as it ensures that the file is properly closed when the block of code inside with is exited.

In [ ]:
with open("example.txt", 'r') as file:
    content = file.read()
    print(content)

# No need to explicitly close the file. It's automatically closed.


# Classes

In [109]:
import random

class BasicDice:
    def __init__(self, sides=6):
        self.sides = sides

    def roll(self):
        return random.randint(1, self.sides)

# Usage:
dice = BasicDice()
print(dice.roll())


2


In [110]:
class IntermediateDice:
    def __init__(self, sides=6):
        self.sides = sides
        self.history = []

    def roll(self):
        result = random.randint(1, self.sides)
        self.history.append(result)
        return result

    def get_roll_history(self):
        return self.history

# Usage:
dice = IntermediateDice()
dice.roll()
dice.roll()
print(dice.get_roll_history())  # Might print [3, 5], for example


[6, 4]


In [112]:
class AdvancedDice:
    def __init__(self, num_dice=1, sides=6):
        self.num_dice = num_dice
        self.sides = sides
        self.history = []

    def roll(self):
        results = [random.randint(1, self.sides) for _ in range(self.num_dice)]
        self.history.extend(results)
        return results

    def get_roll_history(self):
        return self.history

    def get_summary(self):
        return {
            'total_rolls': len(self.history),
            'average_roll': sum(self.history) / len(self.history),
            'max_roll': max(self.history),
            'min_roll': min(self.history)
        }

# Usage:
dice = AdvancedDice(num_dice=2)
dice.roll()
dice.roll()
dice.roll()
dice.roll()
print(dice.get_roll_history())  # Might print [3, 5, 2, 4], for example
print(dice.get_summary())


[2, 4, 5, 3, 2, 4, 4, 2]
{'total_rolls': 8, 'average_roll': 3.25, 'max_roll': 5, 'min_roll': 2}


# Group By pandas

In [114]:
import pandas as pd

data = {
    'Product': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Sales': [100, 150, 200, 50, 300, 210, 400, 50]
}

df = pd.DataFrame(data)
print(df)

grouped = df.groupby('Product').sum()
print(grouped)



  Product  Sales
0       A    100
1       B    150
2       A    200
3       B     50
4       A    300
5       B    210
6       A    400
7       B     50
         Sales
Product       
A         1000
B          460


In [115]:
grouped = df.groupby('Product').agg({'Sales': ['sum', 'mean', 'max', 'min']})
print(grouped)


        Sales                 
          sum   mean  max  min
Product                       
A        1000  250.0  400  100
B         460  115.0  210   50


# Numpy

In [ ]:
import numpy as np
# Showcase of some important NumPy functions

# 1. Creating Arrays:
arr_from_list = np.array([1, 2, 3, 4, 5])
zeros_arr = np.zeros((2, 2))
ones_arr = np.ones((3, 3))
sequence_arr = np.arange(10)
linspace_arr = np.linspace(0, 1, 5)

# 2. Array Operations:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
elementwise_product = a * b
matrix_product = a @ b

# 3. Mathematical Functions:
sin_values = np.sin(np.array([0, np.pi/2, np.pi]))

# 4. Random Module:
random_numbers = np.random.rand(5)
random_integers = np.random.randint(1, 10, size=5)

# Display the results
arr_from_list, zeros_arr, ones_arr, sequence_arr, linspace_arr, elementwise_product, matrix_product, sin_values, random_numbers, random_integers



(array([1, 2, 3, 4, 5]),
 array([[0., 0.],
        [0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([ 4, 10, 18]),
 32,
 array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16]),
 array([0.96380511, 0.96672175, 0.38667587, 0.96408699, 0.83195417]),
 array([1, 2, 7, 5, 3]))